export const CREATE_PAYMENT_SESSION_REQUEST='createPaymentSessionRequest';
export const CREATE_PAYMENT_SESSION_SUCCESS='createPaymentSessionSuccess';
export const CREATE_PAYMENT_SESSION_FAIL='createPaymentSessionFail';